[package]
name = "LiquidityNFT"
version = "1.0.0"
authors = []

[addresses]
LiquidityNFT = "0x9bcf941f3fc088aa508f86f3fccfa1d473316634bd038054fcc709c1ac5c5483"
deployer = "0x2bde0cd8a17e7561d25bc7e98dbfd5eed57ce6c4df0c71171911e608d968c307"
user1 = "0xaaa1"
user2 = "0xaaa2"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
