[package]
name = "LiquidityNFT"
version = "1.0.0"
authors = []

[addresses]
LiquidityNFT = "0xb955219c36bf638334ff07c5625facc30a3be2db6bbba311fcb3732baf05b469"
deployer = "0x7df06ff49afae7c1cf4a44008269b1e5cabb1366629c7837f46b2c39b153f782"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
