[package]
name = "LiquidityNFT"
version = "1.0.0"
authors = []

[addresses]

#deploy-object
contract = "_"

deployer = "0xa9ca66ad7f3886cf727f5aa44837af14112cf3446d0a23fb2ae766147c92b7b8"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
