[package]
name = "LiquidityNFT"
version = "1.0.0"
authors = []

[addresses]

#deploy-object
contract = "_"

#test
#contract = "0xb7265a57ba9c4dd6aea592a829ee9a399db321a9e9d0030e72e8aed8b47d6cbe"

deployer = "0xeb73c29dfea4f17f4d1559208d57687b32e9a3589da19041bdba3e1966082907"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
